import asyncio
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional, Tuple

try:
    from backend.config import settings
except ImportError:
    from config import settings

logger = logging.getLogger("floodsense.services.email")


def _send_smtp_sync(
    subject: str,
    text_content: str,
    html_content: str,
    recipients: List[str],
) -> Tuple[bool, str]:
    """Synchronous worker that connects to SMTP host and delivers email."""
    if not settings.SMTP_PASSWORD:
        logger.warning("SMTP_PASSWORD is not set in environment. Email alert skipped.")
        return False, "SMTP password not configured in backend environment"

    if not recipients:
        return False, "No recipient email addresses provided"

    sender = settings.SMTP_USERNAME or "prajwalupadhyay23@gmail.com"
    host = settings.SMTP_HOST or "smtp.gmail.com"
    port = settings.SMTP_PORT or 587

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"FloodSense Hyderabad <{sender}>"
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(text_content, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    try:
        with smtplib.SMTP(host, port, timeout=15) as server:
            server.ehlo()
            if port == 587:
                server.starttls()
                server.ehlo()
            server.login(sender, settings.SMTP_PASSWORD)
            server.sendmail(sender, recipients, msg.as_string())
        logger.info(f"FloodSense alert email successfully delivered to {recipients}")
        return True, "Alert email delivered successfully"
    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP authentication failed. Please check Gmail App Password.")
        return False, "SMTP authentication failed (invalid App Password)"
    except Exception as e:
        logger.error(f"Failed to send alert email: {e}")
        return False, f"SMTP delivery failed: {str(e)}"


async def send_flood_route_alert_email(
    start_str: str,
    dest_str: str,
    risk_level: str,
    risk_score: float,
    affected_zones: List[str],
    distance_km: float,
    duration_minutes: float,
    recipients: Optional[List[str]] = None,
) -> Tuple[bool, str]:
    """
    Sends an automated flood-risk alert email to configured recipients when a route
    passes through a high or severe waterlogging zone.
    """
    target_recipients = recipients or (
        settings.ALERT_RECIPIENTS
        if isinstance(settings.ALERT_RECIPIENTS, list)
        else [r.strip() for r in str(settings.ALERT_RECIPIENTS).split(",") if r.strip()]
    )

    affected_zone_str = ", ".join(affected_zones) if affected_zones else "Unspecified Waterlogging Corridor"

    subject = "FloodSense Alert: Flood Risk Detected on Your Route"

    text_body = f"""FloodSense Hyderabad

⚠️ FLOOD RISK ALERT

Your selected route passes through a predicted high/severe flood-risk region.

Start:
{start_str}

Destination:
{dest_str}

Risk level:
{risk_level}

Risk score:
{risk_score:.1f}%

Affected zone:
{affected_zone_str}

Route distance:
{distance_km:.1f} km

Estimated travel time:
{duration_minutes:.0f} min

Recommendation:
Please consider an alternate route.

This alert was generated by FloodSense based on the current prediction/risk information.
"""

    html_body = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>FloodSense Route Alert</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0b1120; color: #f8fafc; padding: 24px; margin: 0; }}
    .card {{ max-width: 600px; margin: 0 auto; background-color: #1e293b; border: 1px solid #ef4444; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }}
    .header {{ background: linear-gradient(135deg, #dc2626, #b91c1c); padding: 20px 24px; color: #ffffff; }}
    .header h1 {{ margin: 0; font-size: 20px; font-weight: 700; letter-spacing: -0.5px; }}
    .header p {{ margin: 4px 0 0 0; font-size: 13px; opacity: 0.9; }}
    .content {{ padding: 24px; }}
    .banner {{ background-color: rgba(239, 68, 68, 0.15); border-left: 4px solid #ef4444; padding: 12px 16px; border-radius: 6px; margin-bottom: 20px; }}
    .banner p {{ margin: 0; font-size: 14px; font-weight: 600; color: #fca5a5; }}
    .grid {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
    .grid td {{ padding: 10px 12px; border-bottom: 1px solid #334155; font-size: 13.5px; }}
    .grid td.label {{ color: #94a3b8; font-weight: 500; width: 38%; }}
    .grid td.value {{ color: #f1f5f9; font-weight: 600; }}
    .badge {{ display: inline-block; padding: 3px 10px; border-radius: 9999px; font-size: 12px; font-weight: 700; background-color: #ef4444; color: #ffffff; text-transform: uppercase; }}
    .footer {{ background-color: #0f172a; padding: 16px 24px; font-size: 12px; color: #64748b; border-top: 1px solid #334155; text-align: center; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <h1>FloodSense Hyderabad</h1>
      <p>Automated Urban Waterlogging Early-Warning System</p>
    </div>
    <div class="content">
      <div class="banner">
        <p>⚠️ FLOOD RISK ALERT — High waterlogging probability detected on your active route corridor.</p>
      </div>
      <table class="grid">
        <tr>
          <td class="label">Start Location</td>
          <td class="value">{start_str}</td>
        </tr>
        <tr>
          <td class="label">Destination</td>
          <td class="value">{dest_str}</td>
        </tr>
        <tr>
          <td class="label">Predicted Risk Level</td>
          <td class="value"><span class="badge">{risk_level} ({risk_score:.1f}%)</span></td>
        </tr>
        <tr>
          <td class="label">Affected Risk Zone</td>
          <td class="value" style="color: #f87171;">{affected_zone_str}</td>
        </tr>
        <tr>
          <td class="label">Route Distance</td>
          <td class="value">{distance_km:.1f} km</td>
        </tr>
        <tr>
          <td class="label">Estimated Travel Time</td>
          <td class="value">{duration_minutes:.0f} min</td>
        </tr>
      </table>
      <div style="background-color: #0f172a; border-radius: 8px; padding: 14px; border: 1px solid #334155;">
        <p style="margin: 0; font-size: 13px; color: #cbd5e1; line-height: 1.5;">
          <strong>Recommendation:</strong> Please consider an alternate route or delay travel through this corridor until water recedes.
        </p>
      </div>
    </div>
    <div class="footer">
      This alert was generated automatically by FloodSense based on real-time rainfall and terrain risk predictions.
    </div>
  </div>
</body>
</html>
"""

    return await asyncio.to_thread(
        _send_smtp_sync,
        subject,
        text_body,
        html_body,
        target_recipients,
    )
