import type { FloodReport, FloodAlert } from "./types";

const m = (mins: number) => Date.now() - mins * 60_000;

/** Community report photo placeholders (real street-scene photos; graceful
 *  gradient fallback if offline). */
const photo = (seed: string) => `https://picsum.photos/seed/${seed}/320/200`;

export const MOCK_REPORTS: FloodReport[] = [
  {
    id: "rep-101",
    hotspotId: "hs-moosarambagh",
    location: "Moosarambagh Bridge, NH-65",
    lat: 17.3685,
    lng: 78.513,
    severity: "knee",
    note: "Water crossing the bridge deck, autos turning back. Drain overflowing from the Musi side.",
    photo: photo("floodmoosa"),
    timestamp: m(18),
    status: "verified",
    upvotes: 34,
    source: "community",
    aiConfidence: 0.94,
    waterDepthLabel: "≈ 55 cm",
    verifiedBy: "FloodSense Vision · auto",
  },
  {
    id: "rep-102",
    hotspotId: "hs-tolichowki",
    location: "Tolichowki Flyover underpass",
    lat: 17.397,
    lng: 78.4075,
    severity: "impassable",
    note: "Underpass fully blocked, two cars stalled. Police diverting traffic to the service road.",
    photo: photo("floodtoli"),
    timestamp: m(9),
    status: "pending",
    upvotes: 6,
    source: "community",
  },
  {
    id: "rep-103",
    hotspotId: "hs-malakpet",
    location: "Malakpet Subway",
    lat: 17.3725,
    lng: 78.502,
    severity: "knee",
    note: "Subway closed by traffic police, pumps running.",
    photo: photo("floodmala"),
    timestamp: m(126),
    status: "resolved",
    upvotes: 41,
    source: "community",
    aiConfidence: 0.91,
    waterDepthLabel: "≈ 48 cm",
    verifiedBy: "FloodSense Vision · auto",
  },
  {
    id: "rep-104",
    hotspotId: "hs-alwal",
    location: "Alwal nala crossing, Bollarum Rd",
    lat: 17.5025,
    lng: 78.5125,
    severity: "ankle",
    note: "Nala water spilling onto the road near the school. Two-wheelers wading carefully.",
    photo: photo("floodalwal"),
    timestamp: m(41),
    status: "verified",
    upvotes: 21,
    source: "community",
    aiConfidence: 0.87,
    waterDepthLabel: "≈ 22 cm",
    verifiedBy: "FloodSense Vision · auto",
  },
  {
    id: "rep-105",
    hotspotId: "hs-lbnagar",
    location: "LB Nagar Circle",
    lat: 17.345,
    lng: 78.55,
    severity: "ankle",
    note: "Slow-moving traffic, water pooling at the ORR ramp mouth.",
    timestamp: m(33),
    status: "pending",
    upvotes: 12,
    source: "community",
  },
  {
    id: "rep-106",
    hotspotId: "hs-attapur",
    location: "Attapur main road, near PVNR ramp",
    lat: 17.3575,
    lng: 78.423,
    severity: "ankle",
    note: "Half a lane underwater near the mosque stretch.",
    photo: photo("floodatta"),
    timestamp: m(55),
    status: "verified",
    upvotes: 8,
    source: "community",
    aiConfidence: 0.82,
    waterDepthLabel: "≈ 18 cm",
    verifiedBy: "FloodSense Vision · auto",
  },
  {
    id: "rep-107",
    hotspotId: "hs-uppal",
    location: "Uppal IDL junction",
    lat: 17.407,
    lng: 78.5635,
    severity: "knee",
    note: "Metro work site flooding across two carriageways.",
    photo: photo("flooduppal"),
    timestamp: m(25),
    status: "pending",
    upvotes: 3,
    source: "community",
  },
  {
    id: "rep-108",
    hotspotId: "hs-musheerabad",
    location: "Musheerabad Rd",
    lat: 17.3985,
    lng: 78.4965,
    severity: "ankle",
    note: "Water at divider level, buses making it through.",
    photo: photo("floodmush"),
    timestamp: m(64),
    status: "verified",
    upvotes: 15,
    source: "community",
    aiConfidence: 0.79,
    waterDepthLabel: "≈ 15 cm",
    verifiedBy: "FloodSense Vision · auto",
  },
  {
    id: "rep-109",
    hotspotId: "hs-kothi",
    location: "Kothi Bank Street",
    lat: 17.383,
    lng: 78.481,
    severity: "ankle",
    note: "Shops laying sandbags at thresholds again.",
    timestamp: m(70),
    status: "pending",
    upvotes: 5,
    source: "community",
  },
  {
    id: "rep-110",
    hotspotId: "hs-madhapur",
    location: "Durgam Cheruvu Rd",
    lat: 17.446,
    lng: 78.39,
    severity: "ankle",
    note: "Lake backflow on the cycle track side, road passable.",
    photo: photo("floodmadh"),
    timestamp: m(180),
    status: "resolved",
    upvotes: 27,
    source: "community",
    aiConfidence: 0.85,
    waterDepthLabel: "≈ 20 cm",
    verifiedBy: "FloodSense Vision · auto",
  },
];

export const MOCK_ALERTS: FloodAlert[] = [
  {
    id: "alr-201",
    hotspotId: "hs-moosarambagh",
    title: "Severe risk · Moosarambagh Bridge",
    message:
      "Water level rising ~4 cm every 10 min. NH-65 stretch likely impassable within 45 min. Avoid via Chaderghat Flyover → Inner Ring Rd (+11 min).",
    level: "severe",
    channel: "SMS",
    timestamp: m(12),
    read: false,
    routeHint: "via Chaderghat Flyover → Inner Ring Rd",
  },
  {
    id: "alr-202",
    hotspotId: "hs-tolichowki",
    title: "High risk · Tolichowki underpass",
    message:
      "Community report confirmed impassable. Traffic police diverting. Use Fateh Nagar bridge → Old Mumbai Hwy (+14 min).",
    level: "high",
    channel: "WhatsApp",
    timestamp: m(28),
    read: false,
    routeHint: "via Fateh Nagar bridge → Old Mumbai Hwy",
  },
  {
    id: "alr-203",
    title: "IMD nowcast · rainfall cell NW Hyderabad",
    message:
      "22 mm/hr cell tracked over Kukatpally–Bachupally, moving SE. Expect waterlogging at Nizampet & Alwal nalas within 90 min.",
    level: "moderate",
    channel: "Push",
    timestamp: m(46),
    read: true,
  },
  {
    id: "alr-204",
    hotspotId: "hs-malakpet",
    title: "Resolved · Malakpet Subway",
    message:
      "Water pumped out by GHMC crew #12. Subway reopened to light vehicles. Monitor for next spell.",
    level: "info",
    channel: "SMS",
    timestamp: m(124),
    read: true,
  },
  {
    id: "alr-205",
    title: "Monsoon advisory · Musi corridor",
    message:
      "Avoid Musi-bank roads (Attapur, Chaderghat, Moosarambagh) between 6–9 PM tonight during peak discharge.",
    level: "moderate",
    channel: "WhatsApp",
    timestamp: m(302),
    read: true,
  },
];
